---
title: "Stratigraphic Paleobiology for fossil occurrences"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Stratigraphic Paleobiology for fossil occurrences}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(StratPal)
```

```{r, eval=FALSE}
remotes::install_github(repo = "MindTheGap-ERC/admtools",
                        build_vignettes = TRUE,
                        ref = "HEAD",
                        dependencies = TRUE)
```


```{r}
library("admtools")
```
```{r}
p = p3(10, 0, 2)
```


```{r}
dist = scenarioA$dist_from_shore[2]

# define age-depth model and attach units to it
adm = tp_to_adm(t = scenarioA$t_myr,
                h = scenarioA$h_m[,dist],
                T_unit = "Myr",
                L_unit = "m")
# plot age-depth model
plot(adm,
     lwd_acc = 2,   # plot thicker lines for accumulative intervals (lwd = line width)
     lty_destr = 0) # don't plot destructive intervals (lty = line type)
T_axis_lab() # add time axis label
L_axis_lab() # add length axis label
```

```{r}
p3(rate = 100, from = min_time(adm), to = max_time(adm)) |>                  # simulate fossil occurrences in time
  get_height(adm, t = _, destructive = FALSE) |>    #   transfrom into depth domain
  hist(breaks = seq(min_height(adm), to = max_height(adm), length.out = 20),
      main = "Fossil occurrences",
       xlab = "Height [m]")
```

```{r}
t = scenarioA$t_myr
wd = scenarioA$wd_m[,"2km"]
f = cnd(20, 10, 40)
w = seq(0, 50, by = 1)
plot(w, f(w))

plot(x = t,
     y = f(wd),
     type = "l",
     xlab = "Time [Myr]",
     ylab = "Niche Preference [0 = hate it, 1 = love it]")
```

```{r}
 y = p3(30, from = min_time(adm), to = max_time(adm), n = 1000)


apply_niche_pref(y, niche = cnd(10, 10, 40), temp_change = approxfun(t, wd)) |> hist()

temp_change = approxfun(t, wd, rule = 2)
plot(t, temp_change(t))
niche = cnd(2, 5, 40)
w = seq(0, 50, by = 1)
plot(w, niche(w))
plot(t, niche(temp_change(t)), type = "l")
f = function(x) niche(temp_change(x))
xx = sort(thin(y, f))
hist(xx, breaks = seq(0, 2, by = 0.05))

```

